import os
from openai import OpenAI
from dotenv import load_dotenv

client = OpenAI()

# description = "Play in a band with friends or perform solo on stage with hit music by your favorite artists in Fortnite Festival! On the Main Stage, play a featured rotation of Jam Tracks. Compete against friends for the best performance or team up to climb the leaderboards. The festival is just beginning with more Jam Tracks, Music Icons, concerts, and stages coming soon. Take your stage in Fortnite Festival!"
base_prompt = """
Game 	Creator Name	Description	Created In	Release Date	Last Update	Age Rating	Tags	Players Now	ALL Time Peak
Battle Royale	epic	The battle is building!Drop into the Battle Royale. Loot, build, explore, and fight in a game of 100 players competing to be the last one standing.	Unknown	30-Jun-22	30-Jun-22	Teen / 12		281,587	3,109,888
Bed Wars	theboydilly	 Teams of Three Destroy Opponent's Beds Protect Your Bed Upgrade Your Base With Diamonds	UEFN	20-Aug-23	6-Jun-24	Teen / 7	tycoon, base, pvp, trios, 	7,389	66,058
LEGO Fortnite	epic	Explore vast, open worlds where the magic of LEGO building and Fortnite collide. Find the ultimate survival crafting LEGO adventure in Fortnite!	LEGO	11-Aug-22	11-Aug-22	Everyone 10+ / 7	survival, co-op, open world, sandbox, 	50,943	2,447,763
100 DAYS IN ISOLATION	goldstudio	 Wrecked SEASON UPDATE  Survive 100 Days  Reference to the MrBeast channel Updated MYSTERY BOX Perks & NITRO  Action PVE with Friends  Creative 2.0 | UEFN  Feedback, @Gold_Studio_	UEFN	3-Jan-24	2-Jun-24	Teen / 12	creatures, action, survival horror, pve, 	4,853	45,836
The Pit - Free For All	geerzy	 Your Scoreboard Stats Save Reset Builds Every 10 min 5 Coins per Elimination All Weapons	UEFN	19-Apr-20	5-Jun-24	Teen / 12	free for all, practice, pvp, respawn, 	38,592	117,310
Ranked Zero Build	epic	Just like traditional Zero Build, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		18,047	166,317
BOX PVP 	hive	 NEW! MYTHIC HAVOC MODE CLASSIC BOX FIGHT BOXED LIKE A FISH 200 PUMP IS BACK WINNER GETS GOLD PUMP ELIMS AND WINS SAVE	UEFN	28-Jul-22	9-Jun-24	Teen / 12	boxfight, practice, pvp, 	4,569	130,644
TILTED ZONE WARS 	prettyboy	 Classic Solo Zone Wars  Fun Loot & Items  Name Tags ON  Nostalgic 	UEFN	6-Aug-19	5-Jun-24	Teen / 12	practice, zonewars, pvp, free for all, 	12,481	212,530
Zero Build - Battle Royale	epic	All battle, no building!Zero Build is all the action, loot, and progression of classic Battle Royale, without the Building! Players now have a recharging Overshield for added defense as they fight to be the last one standing.	Unknown	30-Jun-22	30-Jun-22	Teen / 12		214,735	1,405,384
MURDER MYSTERY	goodgamers	 Survivors: Survive the Murderer Murderer: Eliminate all Survivors Sheriff: Eliminate the Murderer	UEFN	20-Oct-23	9-Jun-24	Teen / 7	party game, role playing, survival horror, 	4,974	36,210
Ranked Battle Royale	epic	Just like classic Battle Royale, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		103,930	1,440,170
 SPEED REALISTICS 2v2 - FINEST 	finest	 2v2 Realistics Speed Realistics Enabled Top 250 Leaderboard Updated Weekly Rank up to Unreal by Winning Lofi Beats Made in UEFNThis map is used by the best pros placing in tournaments. There are custom loadout selectors, more than 27 POIs, a ranked leaderboard going all the way to top 250 & lo-fi beats to listen to. Practice against friends via the matchmaking system to reach the highest rank and submit your leaderboard score.	UEFN	31-Dec-20	7-Jun-24	Teen / 12		5,602	8,640
Bed Wars	theboydilly	 Teams of Three Destroy Opponent's Beds Protect Your Bed Upgrade Your Base With Diamonds	UEFN	20-Aug-23	6-Jun-24	Teen / 7	tycoon, base, pvp, trios, 	9,748	66,058
Bio's TRIO - Zone Wars	bio	Play the legendary Bios Trio Zone Wars, the completely free 15 player Zone Wars mode.One clean map, Many cool features, Last team standing wins!LATEST UPDATE ADDED COSMETICS Secret vaultFeaturesDaily rewardsRespawn disabledAchievementsCommunity votingRecieve a crown for the winAutomatic team selectionCustomize weapons5 teamsChoose your teamRandom weapons and items + vending mashinesEliminations save	UEFN	11-Apr-20	4-Jun-24	Teen / 12	zonewars, practice, trios, pvp, 	6,783	60,798
1v1 Build Fights! [4.6.4]	raider464	 Simplistic 1v1 Map Always Updated Fully AutomaticFind Opponents through matchmaking!	UEFN	3-Nov-20	25-May-24	Teen / 12		8,671	32,829
SUPER RED VS BLUE 	typicalgamer	 New ALL Chapter 5 Season 2 Weapons! Most Fun EVER Amazing Super Powers Super Vault and Supply Drops 10 Gold Coins per Elimination Earn Points to Rank Up to Unreal Complete Achievements for Rewards Frequent Updates with all the new content! Eliminations and Ranks Save	UEFN	27-Sep-23	8-Jun-24	Teen / 12		11,718	80,589
1v1 Build Fights! [4.6.4]	raider464	 Simplistic 1v1 Map Always Updated Fully AutomaticFind Opponents through matchmaking!	UEFN	3-Nov-20	25-May-24	Teen / 12	1v1, competitive, practice, 	5,942	32,829
Save The World	epic	Battle to hold back the monster hordes and explore a vast, destructible world. Build huge forts, craft weapons, find loot and level up.	Unknown	25-Aug-21	1-Oct-21	Teen / 12	pve, 	17,097	76,630
SUPER RED VS BLUE 	typicalgamer	 New ALL Chapter 5 Season 2 Weapons! Most Fun EVER Amazing Super Powers Super Vault and Supply Drops 10 Gold Coins per Elimination Earn Points to Rank Up to Unreal Complete Achievements for Rewards Frequent Updates with all the new content! Eliminations and Ranks Save	UEFN	27-Sep-23	8-Jun-24	Teen / 12		7,696	80,589
BHE 1V1 BUILD FIGHTS   	bhe	FFA Build Fights 1v1 box fights fast action build reset built in UEFN	UEFN	14-Aug-19	24-May-24	Teen / 12	1v1, practice, boxfight, 	13,110	59,144
The Pit - Free For All	geerzy	 Your Scoreboard Stats Save Reset Builds Every 10 min 5 Coins per Elimination All Weapons	UEFN	19-Apr-20	5-Jun-24	Teen / 12	free for all, practice, pvp, respawn, 	21,353	117,310
Ranked Zero Build	epic	Just like traditional Zero Build, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		21,544	166,317
KILLER TYCOON 	cmsg	 Level System & Mission System Unlock different Masks to wear for killing Victims in the City! Complete unique Missions to obtain special items! Buy Custom Supercars and Mobile Killers! Open the Ultra Portal to become the Tycoon King! Explore the Open World with the Subway! Spawn your own Mobile Killers on the map to get more Victims! Hack the Bank System or open the vault in the bank! Can you find all the secrets? Build your own Helicopter to find new secrets!	UEFN	18-Apr-24	7-Jun-24	Teen / 12		2,396	18,113
COLLAB REDvsBLUE 	ab01	26 Collab Items and Super PowersEarn Points to Rank Up to UnrealCustom Scoreboard Eliminations and Ranks Save 10 Gold Coins per EliminationReset builds & Vehicles every 15 minMade in UEFNSHOW YOUR SKILLS	UEFN	8-Jun-24	8-Jun-24	Teen / 12	team deathmatch, sandbox, battle, practice, 	3,460	3,596
CRAZY RED VS BLUE 	rvb	 All Weapons Very Fun Red Vs Blue 10 Coins Per Elimination Custom Scoreboard SAVES Eliminations CHAPTER 5 WEAPONS	UEFN	14-Jun-23	9-Jun-24	Teen / 12	team deathmatch, practice, pvp, 	36,587	163,049
Bio's TRIO - Zone Wars	bio	Play the legendary Bios Trio Zone Wars, the completely free 15 player Zone Wars mode.One clean map, Many cool features, Last team standing wins!LATEST UPDATE ADDED COSMETICS Secret vaultFeaturesDaily rewardsRespawn disabledAchievementsCommunity votingRecieve a crown for the winAutomatic team selectionCustomize weapons5 teamsChoose your teamRandom weapons and items + vending mashinesEliminations save	UEFN	11-Apr-20	4-Jun-24	Teen / 12	zonewars, practice, trios, pvp, 	6,058	60,798
1v1 With Every Gun 	hive	 No Locked or Paid Mythics All Weapons Available Without Waiting 24 Player Free-For-All Fun Vehicles Loadout & Eliminations Save Updated Weekly	Creative 1.0	16-Jun-22	7-Jun-24	Teen / 12	free for all, practice, pvp, respawn, 	2,288	15,862
CRAZY RED VS BLUE 	rvb	 All Weapons Very Fun Red Vs Blue 10 Coins Per Elimination Custom Scoreboard SAVES Eliminations CHAPTER 5 WEAPONS	UEFN	14-Jun-23	9-Jun-24	Teen / 12	team deathmatch, practice, pvp, 	28,842	163,049
MUSHROOM TYCOON 	bpascteam	X1.5 EVENT is here!Build the best Mushroom Base Beat 2 parkour challenges!Collect treasure chests on the mapDifferent pets, Boosts and TrailsFind all the secret	UEFN	31-Jan-24	25-May-24	Teen / 12		8,386	8,426
All Weapons - Free For All	mrmonkeyfn	Free For All arena with all Weapons and Perks! Eliminations and Loadouts Save! Instant Reload on Elimination! Instant Respawn!	UEFN	31-Mar-23	3-Jun-24	Teen / 12	practice, free for all, just for fun, pvp, 	3,526	67,006
The Pit - Free For All	geerzy	 Your Scoreboard Stats Save Reset Builds Every 10 min 5 Coins per Elimination All Weapons	UEFN	19-Apr-20	5-Jun-24	Teen / 12	free for all, practice, pvp, respawn, 	29,726	117,310
Piece Control 2v2 	bullseye	 Leaderboard Intense Boxfight Piece Control Scenarios Career Leaderboard/ Arena Points Best practice in the gameGood for duosGreat 2v2 practice with your duoMade in UEFN / Creative 2.0	UEFN	15-Jan-23	4-Jun-24	Teen / 12	boxfight, practice, duo, 2v2, 	20,893	82,795
TILTED ZONE WARS 	prettyboy	 Classic Solo Zone Wars  Fun Loot & Items  Name Tags ON  Nostalgic 	UEFN	6-Aug-19	5-Jun-24	Teen / 12	practice, zonewars, pvp, free for all, 	7,553	212,530
MINIGAME BOX PVP  50+ Minigames 	minigame	 50+ Minigames: Rising Lava Color Switch Hex-A-Gone Spin Cycle Invisible Knockback Slow-Mo Balloon Pop VOTE For Your Favorite Game!	UEFN	9-Nov-23	9-Jun-24	Teen / 12	boxfight, practice, pvp, minigame, 	5,738	62,742
Team Rumble	epic	Two large teams fight for the Victory Royale in an action-packed mode where the first team to get the target number of eliminations wins! Respawn on elimination is ON for the entire match, and gliders can be freely deployed whenever you are far enough from the ground.	Unknown	3-Aug-21	1-Oct-21	Teen / 12		5,405	53,197
All Weapons - Free For All	mrmonkeyfn	Free For All arena with all Weapons and Perks! Eliminations and Loadouts Save! Instant Reload on Elimination! Instant Respawn!	UEFN	31-Mar-23	3-Jun-24	Teen / 12		6,976	67,006
Festival Main Stage	epic	Play in a band with friends or perform solo on stage with hit music by your favorite artists in Fortnite Festival! On the Main Stage, play a featured rotation of Jam Tracks. Compete against friends for the best performance or team up to climb the leaderboards. The festival is just beginning with more Jam Tracks, Music Icons, concerts, and stages coming soon. Take your stage in Fortnite Festival!	Unknown	12-Sep-22	12-Sep-22	Teen / 12	music, party game, 	12,731	847,466
Rocket Racing	epic	Neon Rush lights up in Rocket Racing. Test your limits on all-new Neon Rush themed tracks for Speed Run and Ranked Racing. Try the Creator Rows to race with your friends on tracks made by the UEFN creator community.	Rocket Racing	30-Nov-23	2-Dec-23	Everyone / 3		5,628	625,683
The Pit - Free For All	geerzy	 Your Scoreboard Stats Save Reset Builds Every 10 min 5 Coins per Elimination All Weapons	UEFN	19-Apr-20	5-Jun-24	Teen / 12	free for all, practice, pvp, respawn, 	27,131	117,310
CUSTOM WEAPONS GUN GAME	troll-king	10 CUSTOM WEAPONSTILTED GUN GAMEONESHOTRANK UP TO UNREALCOMPLETE QUESTSSUPER FUNBECOME THE BEST AMONG 20 PLAYERS	UEFN	6-Jun-24	8-Jun-24	Teen / 12	pvp, free for all, just for fun, gun game, 	5,105	58,046
COLLAB REDvsBLUE 	ab01	26 Collab Items and Super PowersEarn Points to Rank Up to UnrealCustom Scoreboard Eliminations and Ranks Save 10 Gold Coins per EliminationReset builds & Vehicles every 15 minMade in UEFNSHOW YOUR SKILLS	UEFN	8-Jun-24	9-Jun-24	Teen / 12	team deathmatch, sandbox, battle, practice, 	9,133	13,334
Bio's TRIO - Zone Wars	bio	Play the legendary Bios Trio Zone Wars, the completely free 15 player Zone Wars mode.One clean map, Many cool features, Last team standing wins!LATEST UPDATE ADDED COSMETICS Secret vaultFeaturesDaily rewardsRespawn disabledAchievementsCommunity votingRecieve a crown for the winAutomatic team selectionCustomize weapons5 teamsChoose your teamRandom weapons and items + vending mashinesEliminations save	UEFN	11-Apr-20	4-Jun-24	Teen / 12		5,802	60,798
Ranked Zero Build	epic	Just like traditional Zero Build, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		40,223	166,317
MINIGAME BOX PVP  50+ Minigames 	minigame	 50+ Minigames: Rising Lava Color Switch Hex-A-Gone Spin Cycle Invisible Knockback Slow-Mo Balloon Pop VOTE For Your Favorite Game!	UEFN	9-Nov-23	9-Jun-24	Teen / 12		7,345	62,742
Piece Control 2v2 	bullseye	 Leaderboard Intense Boxfight Piece Control Scenarios Career Leaderboard/ Arena Points Best practice in the gameGood for duosGreat 2v2 practice with your duoMade in UEFN / Creative 2.0	UEFN	15-Jan-23	4-Jun-24	Teen / 12	boxfight, practice, duo, 2v2, 	15,325	82,795
Festival Main Stage	epic	Play in a band with friends or perform solo on stage with hit music by your favorite artists in Fortnite Festival! On the Main Stage, play a featured rotation of Jam Tracks. Compete against friends for the best performance or team up to climb the leaderboards. The festival is just beginning with more Jam Tracks, Music Icons, concerts, and stages coming soon. Take your stage in Fortnite Festival!	Unknown	12-Sep-22	12-Sep-22	Teen / 12	music, party game, 	17,950	847,466
 RED VS BLUE  RUMBLE	rvb	 New All Ch5 Weapons Added ENDLESS TEAM DEATHMATCH COMBAT POWERUPS AND SECRETS  Rank up from BRONZE to UNREAL 50 Gold Coins per Elimination OP Vault Eliminations and Ranks Save	UEFN	6-Mar-21	7-Jun-24	Teen / 12	team deathmatch, capture the flag, base, action, 	4,201	26,756
 GO GOATED! Zone Wars  *NEW WEAPONS*	theboydilly	 4 Teams Battle  Classic Zone Wars Game Select Your Team Eliminations Save 	UEFN	2-Jun-21	5-Jun-24	Teen / 7	practice, pvp, zonewars, 	33,246	111,777
Piece Control 2v2 	bullseye	 Leaderboard Intense Boxfight Piece Control Scenarios Career Leaderboard/ Arena Points Best practice in the gameGood for duosGreat 2v2 practice with your duoMade in UEFN / Creative 2.0	UEFN	15-Jan-23	4-Jun-24	Teen / 12	boxfight, practice, duo, 2v2, 	12,115	82,795
Ranked Zero Build	epic	Just like traditional Zero Build, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		28,476	166,317
Battle Royale	epic	The battle is building!Drop into the Battle Royale. Loot, build, explore, and fight in a game of 100 players competing to be the last one standing.	Unknown	30-Jun-22	30-Jun-22	Teen / 12		205,197	3,109,888
PAL TYCOON 	camrin	- Mining & Harvesting - Claim Pets - Earn Keys - Keys Increase Production - Keys are saved - Boss Battle Replayable Tycoon! 	UEFN	12-May-24	8-Jun-24	Teen / 12	tycoon, simulator, boss battle, casual, 	2,198	6,621
Bio's TRIO - Zone Wars	bio	Play the legendary Bios Trio Zone Wars, the completely free 15 player Zone Wars mode.One clean map, Many cool features, Last team standing wins!LATEST UPDATE ADDED COSMETICS Secret vaultFeaturesDaily rewardsRespawn disabledAchievementsCommunity votingRecieve a crown for the winAutomatic team selectionCustomize weapons5 teamsChoose your teamRandom weapons and items + vending mashinesEliminations save	UEFN	11-Apr-20	4-Jun-24	Teen / 12	zonewars, practice, trios, pvp, 	5,249	60,798
RAPPER 2 TYCOON	large_ape	Become the ultimate rap god and perform in front of thousands of fans!Upgrade your crib into a multi-level mansion in the heart of the cityHire agents to book gigs that take you from BROKE to G.O.A.T.Complete missions to discover lost records and unearth alien life forcesRule the underground to grow your empireDevelop relationships with storyline characters on your journeyUnlock all seven levels and save your progress through REBIRTHSCan you make it all the way to the top?	UEFN	3-May-24	5-Jun-24	Teen / 7	tycoon, casual, just for fun, simulator, 	2,269	11,525
PANDVIL Box Fight (2v2) 	pandvil	Made By PANDVIL(2 vs 2) Box Fight MatchmakingNear 0 wait between roundsRanks, Cosmetics and much moreWhen eliminated spectate OR parkourLIFETIME WIN & ELIMINATION leaderboards	UEFN	10-Nov-20	6-Jun-24	Teen / 12	boxfight, practice, duo, 2v2, 	5,104	89,676
Bed Wars	theboydilly	 Teams of Three Destroy Opponent's Beds Protect Your Bed Upgrade Your Base With Diamonds	UEFN	20-Aug-23	6-Jun-24	Teen / 7	tycoon, base, pvp, trios, 	8,528	66,058
1v1 Build Fights! [4.6.4]	raider464	 Simplistic 1v1 Map Always Updated Fully AutomaticFind Opponents through matchmaking!	UEFN	3-Nov-20	25-May-24	Teen / 12	1v1, competitive, practice, 	6,312	32,829
SUPER RED VS BLUE 	typicalgamer	 New ALL Chapter 5 Season 2 Weapons! Most Fun EVER Amazing Super Powers Super Vault and Supply Drops 10 Gold Coins per Elimination Earn Points to Rank Up to Unreal Complete Achievements for Rewards Frequent Updates with all the new content! Eliminations and Ranks Save	UEFN	27-Sep-23	8-Jun-24	Teen / 12		8,422	80,589
LEGO Fortnite	epic	Explore vast, open worlds where the magic of LEGO building and Fortnite collide. Find the ultimate survival crafting LEGO adventure in Fortnite!	LEGO	11-Aug-22	11-Aug-22	Everyone 10+ / 7	survival, co-op, open world, sandbox, 	41,467	2,447,763
BHE 1V1 BUILD FIGHTS   	bhe	FFA Build Fights 1v1 box fights fast action build reset built in UEFN	UEFN	14-Aug-19	24-May-24	Teen / 12	1v1, practice, boxfight, 	6,133	59,144
< RASF	rsaf	  SURVIVAL OF THE BEST	Creative 1.0	11-May-23	29-May-24	Teen / 12	zonewars, battle, arena, competitive, 	4,067	8,850
Festival Main Stage	epic	Play in a band with friends or perform solo on stage with hit music by your favorite artists in Fortnite Festival! On the Main Stage, play a featured rotation of Jam Tracks. Compete against friends for the best performance or team up to climb the leaderboards. The festival is just beginning with more Jam Tracks, Music Icons, concerts, and stages coming soon. Take your stage in Fortnite Festival!	Unknown	12-Sep-22	12-Sep-22	Teen / 12	music, party game, 	11,024	847,466
Unrealistic Driving Island	uhafa77	 4x4 km Open world map CH5 S3 weapons and vehicles FFA Collect items scattered around the island Finding hidden Octane scattered around. Unlimited fuel and boost. Enjoy driving with friends.	UEFN	28-Apr-24	26-May-24	Teen / 12	open world, race, driver simulator, free for all, 	2,058	48,414
 RED VS BLUE  RUMBLE	rvb	 New All Ch5 Weapons Added ENDLESS TEAM DEATHMATCH COMBAT POWERUPS AND SECRETS  Rank up from BRONZE to UNREAL 50 Gold Coins per Elimination OP Vault Eliminations and Ranks Save	UEFN	6-Mar-21	7-Jun-24	Teen / 12	team deathmatch, capture the flag, base, action, 	5,250	26,756
LEGO Fortnite	epic	Explore vast, open worlds where the magic of LEGO building and Fortnite collide. Find the ultimate survival crafting LEGO adventure in Fortnite!	LEGO	11-Aug-22	11-Aug-22	Everyone 10+ / 7	survival, co-op, open world, sandbox, 	37,024	2,447,763
ONE SHOT GUN GAME  AIM	sneznyj	PVP/PVEQUESTSSECRETSINFINITE WEAPONSENDLESS ROUNDSINFINITE TIMEENDLESS FUNTRAIN YOUR AIMFIGHT THE BOTSBECOME THE BEST AMONG 12 PLAYERS	UEFN	3-May-24	3-May-24	Teen / 12	gun game, one shot, pvp, training, 	2,107	9,222
OnlyUp Fortnite! 	army	OnlyUp Fortnite, with an Altitude Meter and Timer! If you fall, you restart from the beginning... Don't fall and reach the top by passing every season of Fortnite Chapter 1! 	UEFN	15-Jun-23	25-May-24	Everyone / 3	deathrun, just for fun, parkour, escape, 	5,429	113,933
Ranked Battle Royale	epic	Just like classic Battle Royale, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		160,456	1,440,170
Piece Control 2v2 	bullseye	 Leaderboard Intense Boxfight Piece Control Scenarios Career Leaderboard/ Arena Points Best practice in the gameGood for duosGreat 2v2 practice with your duoMade in UEFN / Creative 2.0	UEFN	15-Jan-23	4-Jun-24	Teen / 12	boxfight, practice, duo, 2v2, 	10,964	82,795
Zero Build - Battle Royale	epic	All battle, no building!Zero Build is all the action, loot, and progression of classic Battle Royale, without the Building! Players now have a recharging Overshield for added defense as they fight to be the last one standing.	Unknown	30-Jun-22	30-Jun-22	Teen / 12		148,438	1,405,384
 GO GOATED! Zone Wars  *NEW WEAPONS*	theboydilly	 4 Teams Battle  Classic Zone Wars Game Select Your Team Eliminations Save 	UEFN	2-Jun-21	5-Jun-24	Teen / 7	practice, pvp, zonewars, 	23,342	111,777
SKYBOX	bifrost	SANDBOX IN THE SKY! HIT CHEST!UPGRADE EVERYTHING! BUILD A SKYTOWN! EXPLORE A MASSIVE WORLD IN THE SKY	Creative 1.0	4-Feb-23	31-May-24	Teen / 7	creatures, open world, tycoon, pve, 	1,833	15,910
 GO GOATED! Zone Wars  *NEW WEAPONS*	theboydilly	 4 Teams Battle  Classic Zone Wars Game Select Your Team Eliminations Save 	UEFN	2-Jun-21	5-Jun-24	Teen / 7	practice, pvp, zonewars, 	25,953	111,777
180 LEVEL OBBY PARKOUR 	s.w.a.t	 180 STAGES Extra stages with Random gifts Time Your Run Shop Custom HUD Leaderboard Made In UEFN/Verse Updated 	UEFN	28-Mar-24	16-Apr-24	Teen / 7		2,392	2,508
Ranked Battle Royale	epic	Just like classic Battle Royale, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		190,181	1,440,170
Team Rumble	epic	Two large teams fight for the Victory Royale in an action-packed mode where the first team to get the target number of eliminations wins! Respawn on elimination is ON for the entire match, and gliders can be freely deployed whenever you are far enough from the ground.	Unknown	3-Aug-21	1-Oct-21	Teen / 12		4,307	53,197
 RED VS BLUE  RUMBLE	rvb	 New All Ch5 Weapons Added ENDLESS TEAM DEATHMATCH COMBAT POWERUPS AND SECRETS  Rank up from BRONZE to UNREAL 50 Gold Coins per Elimination OP Vault Eliminations and Ranks Save	UEFN	6-Mar-21	7-Jun-24	Teen / 12		6,565	26,756
LEGO Fortnite	epic	Explore vast, open worlds where the magic of LEGO building and Fortnite collide. Find the ultimate survival crafting LEGO adventure in Fortnite!	LEGO	11-Aug-22	11-Aug-22	Everyone 10+ / 7	survival, co-op, open world, sandbox, 	67,482	2,447,763
OnlyUp Fortnite! 	army	OnlyUp Fortnite, with an Altitude Meter and Timer! If you fall, you restart from the beginning... Don't fall and reach the top by passing every season of Fortnite Chapter 1! 	UEFN	15-Jun-23	25-May-24	Everyone / 3		6,207	113,933
Prison Breakout RP	fnbreakout	Prison Breakout is an open world game of Cops and Robbers, escape prison to start your adventure, or be a guard and protect the city!  24 Player Lobby Plan and Complete Heists Upgrade your gear Purchase Apartments & Villas Find Secrets Complete Quests Unlock Achievements 1st & 3rd Person View Progress Saves	UEFN	10-Jan-21	6-Jun-24	Teen / 12	role playing, open world, just for fun, race, 	1,795	31,222
MURDER MYSTERY	goodgamers	 Survivors: Survive the Murderer Murderer: Eliminate all Survivors Sheriff: Eliminate the Murderer	UEFN	20-Oct-23	9-Jun-24	Teen / 7	party game, role playing, survival horror, 	5,628	36,210
MUSHROOM TYCOON 	bpascteam	X1.5 EVENT is here!Build the best Mushroom Base Beat 2 parkour challenges!Collect treasure chests on the mapDifferent pets, Boosts and TrailsFind all the secret	UEFN	31-Jan-24	25-May-24	Teen / 12	just for fun, tycoon, simulator, casual, 	5,439	5,484
Bed Wars Klombos [PvP BedWars]	voldex	 Chapter 5 Weapons & Mods! Defend Your Klombo (Bed)! Break Rival Klombos! 4v4v4v4 Battle!	UEFN	2-Mar-22	8-Jun-24	Teen / 12	base, tycoon, pvp, practice, 	1,827	25,277
  PRO	awa	2-20 players compete, either team of the two teams for first place! in an atmosphere of enthusiasm and suspense in this creative map.	UEFN	13-Jul-20	8-Jun-24	Teen / 12	team deathmatch, action, capture the flag, base, 	3,518	11,812
PANDVIL Box Fight (2v2) 	pandvil	Made By PANDVIL(2 vs 2) Box Fight MatchmakingNear 0 wait between roundsRanks, Cosmetics and much moreWhen eliminated spectate OR parkourLIFETIME WIN & ELIMINATION leaderboards	UEFN	10-Nov-20	6-Jun-24	Teen / 12		6,683	89,676
Ranked Battle Royale	epic	Just like classic Battle Royale, with a little more to play for!Battle it out against other players of similar rank. Show off your skills, complete challenges for rewards, and climb the ranks.	Unknown	11-Apr-23	11-Apr-23	Teen / 12		143,470	1,440,170
TILTED ZONE WARS 	prettyboy	 Classic Solo Zone Wars  Fun Loot & Items  Name Tags ON  Nostalgic 	UEFN	6-Aug-19	5-Jun-24	Teen / 12	practice, zonewars, pvp, free for all, 	6,055	212,530
MURDER MYSTERY	goodgamers	 Survivors: Survive the Murderer Murderer: Eliminate all Survivors Sheriff: Eliminate the Murderer	UEFN	20-Oct-23	9-Jun-24	Teen / 7	party game, role playing, survival horror, 	9,045	36,210
CRAZY RED VS BLUE 	rvb	 All Weapons Very Fun Red Vs Blue 10 Coins Per Elimination Custom Scoreboard SAVES Eliminations CHAPTER 5 WEAPONS	UEFN	14-Jun-23	9-Jun-24	Teen / 12	team deathmatch, practice, pvp, 	20,919	163,049
Rocket Racing	epic	Neon Rush lights up in Rocket Racing. Test your limits on all-new Neon Rush themed tracks for Speed Run and Ranked Racing. Try the Creator Rows to race with your friends on tracks made by the UEFN creator community.	Rocket Racing	30-Nov-23	2-Dec-23	Everyone / 3		4,672	625,683

Based on the above game data, for this game description generate 5 game titles
{}
"""

def flow_1(description):
    prompt = base_prompt.format(description)
    completion = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages=[
        {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
        {"role": "user", "content": prompt}
      ]
    )

    return completion.choices[0].message.content

# print(flow_1())
