name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy and Check Service
        uses: Aroha-Labs/nyx-deployment-action@main
        with:
          name: "visceral-flows"
          environment: "prod"
          port: "8000"
